spring:
  profiles:
    include: developmentdb

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      ddl-auto: update


  data:
    jpa:
      repositories:
        enabled: true


  mvc:
    date-format: yyyy-MM-dd hh:mm:ss

  jackson:
    date-format: yyyy-MM-dd hh:mm:ss



logging:
  level:
    com.handicraft.*: debug
