spring:
  profiles:
    include:  development-core

  mvc:
    view:
      prefix: /view/
      suffix: .jsp


server:
  session:
    timeout:  600
  port: 8080


naver:
  client:
    client-id:  XhmXptV7PpE7X_2Zp7lw
    client-secret:  WB43Gka_2U
    access-token-uri: https://nid.naver.com/oauth2.0/token
    user-authorization-uri: https://nid.naver.com/oauth2.0/authorize
    pre-established-redirect-uri: http://localhost:8080/calender/token
    use-current-uri:  false
    #registered-redirect-uri: http://localhost:8080/calender
    token-name: oauth_token
    authentication-scheme:  query
    client-authentication-scheme: query
  resource:
    user-info-uri: https://openapi.naver.com/v1/nid/me

bucketName: www.half-handicraft.com
accessKey: AKIAJQ624S4PDZO5JDFQ
secretKey: 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