spring:
  profiles:
    include: development-core
  jackson:
    serialization:
      fail_on_empty_beans:  false
      WRITE_DATES_AS_TIMESTAMPS : false
  http:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
server:
  port: 9091


